// Auto-generated by `npx convex dev` — do not edit manually.
// This stub is replaced when you run: npx convex dev
import type { AnyFunctionReference } from "convex/server"

type ApiType = {
  sales: {
    listSales: AnyFunctionReference
    createSale: AnyFunctionReference
    updateSale: AnyFunctionReference
    deleteSale: AnyFunctionReference
    getSettings: AnyFunctionReference
    upsertSettings: AnyFunctionReference
    importAll: AnyFunctionReference
  }
}

export const api = {} as unknown as ApiType
export const internal = {} as unknown as ApiType
