// Auto-generated by `npx convex dev` — do not edit manually.
import type { GenericId } from "convex/values"

export type TableNames = "sales" | "settings"
export type Id<T extends TableNames> = GenericId<T>
